name: skysolve/release

on:
  pull_request:
    branches:
      - main

  push:
    tags:
      - "v*.*.*" # e.g., v1.0.0

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        go: ["1.23.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup our base Go environment 🧬
      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Import GPG Key 🔑
        id: gpgkey
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set GoReleaser Arguments
        id: release_args
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "args=release --clean --snapshot" >> $GITHUB_OUTPUT
          else
            echo "args=release --clean" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}

      - name: Run GoReleaser 🛸
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: ${{ steps.release_args.outputs.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.gpgkey.outputs.fingerprint }}
